[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  node_bundler = "esbuild"
  external_node_modules = ["cheerio", "node-vibrant"]

[dev]
  functions = "netlify/functions"
  functionsPort = 8888
