[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  external_node_modules = [
    "cheerio",
    "node-vibrant",
    "puppeteer-core",
    "chrome-aws-lambda"
  ]
  
[dev]
  functions = "netlify/functions"
  functionsPort = 8888
